spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backend
    username: backend
    password: backend
    initialization-mode: always     # Initialize the schema of the database
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create    # Letting the Hibernate to create the database based of the Object Definition (Not the best practice) instead use the database migration tool (liquibase or Flyway)